### ISSUE TITLE
Inline-math scripts' visibility in dark mode

### ISSUE THREAD

**Issue by Rainybunny** [cayxc/Mdmdt#6]
In dark mode, the color of inline-math script is dark purple (by default), which is really hard to recognize since the background is also dark.

A possible way to solve this is to add the snippet below:

```css
.md-inline-math script {
  color: #cceeff; /* or any light color, for dark themes */
}
```
